### ISSUE TITLE
[BUG] `refine-nextjs-router` is incompatible with `nextjs ^12.0.3`

### ISSUE THREAD

**Issue by wy-z** [pankod/refine#1233]
First of all, thank you for your great work~

**Describe the bug**
`refine-nextjs-router` is incompatible with `nextjs ^12.0.3`

**To Reproduce**
1. `npx superplate-cli xsky-asst`
2. `Select your project type › refine-nextjs`
3. Edit `package.json`, set `next` version to `^12.0.3`
4. `yarn install`
5. `yarn dev`

**Screenshots**
![image](https://user-images.githubusercontent.com/4213483/141421041-6d57334e-a0dd-422e-856f-4d4fd00c29e5.png)
![image](https://user-images.githubusercontent.com/4213483/141421792-2b43b594-de2a-4d79-bc58-f53506af695e.png)
```
Server Error
TypeError: Cannot read properties of null (reading 'push')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
useHistory
file:///Users/weiyang/Ones/fun/xsky-asst/frontend-ng/xsky-asst/node_modules/@pankod/refine-nextjs-router/dist/refine-nextjs-router.cjs.development.js (44:25)
NextRouteComponent
file:///Users/weiyang/Ones/fun/xsky-asst/frontend-ng/xsky-asst/node_modules/@pankod/refine-nextjs-router/dist/refine-nextjs-router.cjs.development.js (134:21)
processChild
file:///Users/weiyang/Ones/fun/xsky-asst/frontend-ng/xsky-asst/node_modules/react-dom/cjs/react-dom-server.node.development.js (3353:14)
resolve
file:///Users/weiyang/Ones/fun/xsky-asst/frontend-ng/xsky-asst/node_modules/react-dom/cjs/react-dom-server.node.development.js (3270:5)
ReactDOMServerRenderer.render
file:///Users/weiyang/Ones/fun/xsky-asst/frontend-ng/xsky-asst/node_modules/react-dom/cjs/react-dom-server.node.development.js (3753:22)
ReactDOMServerRenderer.read
file:///Users/weiyang/Ones/fun/xsky-asst/frontend-ng/xsky-asst/node_modules/react-dom/cjs/react-dom-server.node.development.js (3690:29)
Object.renderToString
file:///Users/weiyang/Ones/fun/xsky-asst/frontend-ng/xsky-asst/node_modules/react-dom/cjs/react-dom-server.node.development.js (4298:27)
Object.renderPage
file:///Users/weiyang/Ones/fun/xsky-asst/frontend-ng/xsky-asst/node_modules/next/dist/server/render.js (621:45)
Object.defaultGetInitialProps
file:///Users/weiyang/Ones/fun/xsky-asst/frontend-ng/xsky-asst/node_modules/next/dist/server/render.js (301:51)
Function.getInitialProps
node_modules/next/dist/pages/_document.js (145:19)
```

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Chrome
 - Version: 95.0.4638.69

**Comment by omeraplak** [comment]
Hey @wy-z ,
We've released refine-nextjs-router@2.0.15. Could you approve this issue fixed?

**Comment by wy-z** [comment]
`@pankod/refine-nextjs-router@2.0.15` worked for me, thanks again!

**Comment by IgnusG** [comment]
I've just bootstrapped refine from the documentation tutorial https://refine.dev/docs/getting-started/overview/#quick-start and selected Airtable as the provider. It then gave me a similar error as above. I saw that the router in the starter is not set to that version but I still get the error even after I changed it manually.

<details>
<summary>Error</details>
<pre>
error - TypeError: Cannot read properties of null (reading 'push')
    at useHistory (/home/jonathan/projects/live-tabs/tutorial/node_modules/@pankod/refine-nextjs-router/dist/refine-nextjs-router.cjs.development.js:44:25)
    at NextRouteComponent (/home/jonathan/projects/live-tabs/tutorial/node_modules/@pankod/refine-nextjs-router/dist/refine-nextjs-router.cjs.development.js:134:21)
    at processChild (/home/jonathan/projects/live-tabs/tutorial/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/home/jonathan/projects/live-tabs/tutorial/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/jonathan/projects/live-tabs/tutorial/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/jonathan/projects/live-tabs/tutorial/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/home/jonathan/projects/live-tabs/tutorial/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/home/jonathan/projects/live-tabs/tutorial/node_modules/next/dist/server/render.js:596:45)
    at Function.getInitialProps (/home/jonathan/projects/live-tabs/tutorial/.next/server/pages/_document.js:618:19)
    at Object.loadGetInitialProps (/home/jonathan/projects/live-tabs/tutorial/node_modules/next/dist/shared/lib/utils.js:69:29) {
  page: '/[resource]'
}
</pre>
</details>

I have only added one resource and followed the tutorial at https://refine.dev/docs/#creating-a-list-page

**Comment by omeraplak** [comment]
Hey @IgnusG,
Could you delete package-lock and node_modules and try "npm i" again?

**Comment by IgnusG** [comment]
Seems that the error stayed the same :(

**Comment by omeraplak** [comment]
> Seems that the error stayed the same :(

Could you try again create a new project with superplate?

**Comment by IgnusG** [comment]
> > Seems that the error stayed the same :(
> 
> Could you try again create a new project with superplate?

Works now! Thanks for the support :)
